// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtwUYCFBXM26no3Kqh4LtxLaZTgzdzYzs',
    appId: '1:306983096617:web:db15500fb3e24db983a738',
    messagingSenderId: '306983096617',
    projectId: 'controledeponto-6d11c',
    authDomain: 'controledeponto-6d11c.firebaseapp.com',
    databaseURL: 'https://controledeponto-6d11c-default-rtdb.firebaseio.com',
    storageBucket: 'controledeponto-6d11c.appspot.com',
    measurementId: 'G-T5J1F9ZTFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlqvBEcfw2Zoc6ucqvbNvjjjqOgI_Orc',
    appId: '1:306983096617:android:bb585de34e224a9f83a738',
    messagingSenderId: '306983096617',
    projectId: 'controledeponto-6d11c',
    databaseURL: 'https://controledeponto-6d11c-default-rtdb.firebaseio.com',
    storageBucket: 'controledeponto-6d11c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWh7GcMx6Ix5BnwANlHzz3_-UWjKgbQfk',
    appId: '1:306983096617:ios:095c82d6f323e00283a738',
    messagingSenderId: '306983096617',
    projectId: 'controledeponto-6d11c',
    databaseURL: 'https://controledeponto-6d11c-default-rtdb.firebaseio.com',
    storageBucket: 'controledeponto-6d11c.appspot.com',
    iosBundleId: 'com.example.gerenciaDePonto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWh7GcMx6Ix5BnwANlHzz3_-UWjKgbQfk',
    appId: '1:306983096617:ios:095c82d6f323e00283a738',
    messagingSenderId: '306983096617',
    projectId: 'controledeponto-6d11c',
    databaseURL: 'https://controledeponto-6d11c-default-rtdb.firebaseio.com',
    storageBucket: 'controledeponto-6d11c.appspot.com',
    iosBundleId: 'com.example.gerenciaDePonto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtwUYCFBXM26no3Kqh4LtxLaZTgzdzYzs',
    appId: '1:306983096617:web:a7d141e856555da683a738',
    messagingSenderId: '306983096617',
    projectId: 'controledeponto-6d11c',
    authDomain: 'controledeponto-6d11c.firebaseapp.com',
    databaseURL: 'https://controledeponto-6d11c-default-rtdb.firebaseio.com',
    storageBucket: 'controledeponto-6d11c.appspot.com',
    measurementId: 'G-F7VG84VRDF',
  );
}
